### ISSUE TITLE
Datasets list

### ISSUE THREAD

**Issue by gsrujana** [xinghaochen/awesome-hand-pose-estimation#1]
Hi, thank you for the collection of papers! This is more of suggestion than an issue. Could you also provide a comprehensive list of datasets and challenges available for hand pose estimation. Thank again for this page, it is helpful!

**Comment by xinghaochen** [comment]
Hi, thanks for your good suggestion. I will consider providing the list of datasets in the future. Any pull requests about this would be appreciated.
As it would be a while before I can update the list, you can have a look at [this paper](https://arxiv.org/abs/1704.02612) or [this page](http://arrummzen.net/#HandData) for some details of existing hand pose datasets and [this document](https://arxiv.org/abs/1707.02237) for an ongoing challenge.

**Comment by xinghaochen** [comment]
I have already added a list of datasets and challenge (stay tuned). 
Check the repo.
