### ISSUE TITLE
Paper link error

### ISSUE THREAD

**Issue by geliuhao** [xinghaochen/awesome-hand-pose-estimation#16]
2019 CVPR
3D Hand Shape and Pose Estimation from a Single RGB Image
https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxnZWxpdWhhb250dXxneDo3ZjE0ZjY3OWUzYjJkYjA2

**Comment by xinghaochen** [comment]
Hi Liuhao,
Thanks for pointing it out. I have just fixed this problem.
