### ISSUE TITLE
How to choose these values in pixeltoworld function?

### ISSUE THREAD

**Issue by JasOlean** [xinghaochen/awesome-hand-pose-estimation#17]
```
def get_param(dataset):
    if dataset == 'icvl':
        return 240.99, 240.96, 160, 120
    elif dataset == 'nyu':
        return 588.03, -587.07, 320, 240
    elif dataset == 'msra':
        return 241.42, 241.42, 160, 120
```

**Comment by xinghaochen** [comment]
These values are intrinsic parameters of the depth cameras that are used for data collection.

**Comment by JasOlean** [comment]
So, how to choose about synthetic images for that?

**Comment by JasOlean** [comment]
In draw map, what does that mean 'Fraction of frames within distance'?

**Comment by xinghaochen** [comment]
This means the proportion of test frames whose maximum error falls below a threshold, see [evaluation metrics](https://github.com/xinghaochen/awesome-hand-pose-estimation/blob/master/evaluation/README.md#evaluation-metric).

**Comment by JasOlean** [comment]
So, max-frame is 'the proportion of test frames whose maximum error falls below a threshold'.
mean-frame is 'The proportion of test frames whose average error falls below a threshold', and 
joint is 'The proportion of all joints whose error falls below a threshold'.

is it correct? There is no for method 1.

**Comment by xinghaochen** [comment]
> So, max-frame is 'the proportion of test frames whose maximum error falls below a threshold'.
> mean-frame is 'The proportion of test frames whose average error falls below a threshold', and
> joint is 'The proportion of all joints whose error falls below a threshold'.

Yes, your understanding is correct.

> There is no for method 1.

I am a bit confused about what you exactly mean for "method 1".
