### ISSUE TITLE
Annotated data with visibility labeling 

### ISSUE THREAD

**Issue by abaghiyan** [xinghaochen/awesome-hand-pose-estimation#18]
Is there a method or database with labels on visibility of annotated joints, as there are many cases that joints are annotated but not visible (enclosed by other objects). The labeling in [Coco data format](http://cocodataset.org/#format-data) allows such labeling as "not labeled", "labeled but invisible", and "labeled and visible" types of annotations.

**Comment by xinghaochen** [comment]
Hi, please see [CMU Panoptic HandDB](http://domedb.perception.cs.cmu.edu/handdb.html), which annoatates the visibility of each hand joint (see the format [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#hand-output-format)).

**Comment by abaghiyan** [comment]
Thank you very much!

**Comment by abaghiyan** [comment]
In the Rendered Handpose Dataset (RHD) there exist labeling for visibility ["21 Keypoints for each hand with their uv coordinates in the image frame, xyz coordinates in the world frame and a visibility indicator"](https://lmb.informatik.uni-freiburg.de/resources/datasets/RenderedHandposeDataset.en.html).

**Comment by xinghaochen** [comment]
Thanks! It's will be helpful for others.
