### ISSUE TITLE
Released  code

### ISSUE THREAD

**Issue by weiguochow** [xinghaochen/awesome-hand-pose-estimation#20]
Hello,
Can you release the code of paper `SHPR-Net: Deep Semantic Hand Pose Regression From Point Clouds`.  I am especially interesting about the dataset preprocessed that convert from hand depth map to point cloud data. I am looking forward to your reply! Thank you very much!

**Comment by xinghaochen** [comment]
Hi, sorry for the late reply. Converting depth map to point cloud is quite straight-forward. You can just convert all the pixels from (u, v, d) to (x, y, z) using the intrinsic parameters of the camera, see [here](https://github.com/xinghaochen/awesome-hand-pose-estimation/blob/e29335d581f84ed6d0ce2f7204aa7c00684eb97a/evaluation/src/util.py#L31-L34) for reference. Currently releasing the code of SHPR-Net is not in the schedule yet, but feel free to drop me emails for any questions about this paper :)
