### ISSUE TITLE
How to get these values?

### ISSUE THREAD

**Issue by huangshaoguang** [xinghaochen/awesome-hand-pose-estimation#21]
Hello!Thank you for sharing your great job! I am trying to predict with the CrossInfoNet on a kinect2 online, but I don't konw how to get these values

**Comment by huangshaoguang** [comment]
I meant that these values in the dataset files train_NYU.txt and test_NYU.txt(sorry I can't upload image files):
-133.28715515137 -12.867971420288 761.99810791016
-134.04685974121 -13.173347473145 764.24127197266
-134.10357666016 -13.075632095337 764.19580078125
-133.53086853027 -12.983173370361 763.73486328125
-133.32577514648 -12.786666870117 764.64447021484
-133.78622436523 -12.698698043823 764.64324951172
-134.00987243652 -12.755805969238 764.63012695312
-133.62202453613 -12.624512672424 762.92218017578
-133.67845153809 -12.730281829834 763.50604248047
-134.78399658203 -13.032011032104 765.18389892578
-134.74922180176 -13.012309074402 764.46911621094
-134.46246337891 -12.850967407227 764.93353271484
-133.70986938477 -12.967323303223 765.94787597656
-133.34596252441 -12.812543869019 765.18524169922
-133.20928955078 -12.192935943604 765.54956054688
-133.04669189453 -12.088114738464 764.86364746094
-132.46058654785 -12.180419921875 766.19268798828
-132.76304626465 -12.127345085144 766.00592041016
-132.25242614746 -12.21319770813 765.89636230469
-131.84208679199 -12.034255981445 764.39770507812
-132.04342651367 -12.424405097961 763.42590332031
-132.0329284668 -12.583179473877 764.69793701172
-133.59399414062 -12.915204048157 766.18103027344
-132.97647094727 -12.674821853638 764.54516601562
-133.33424377441 -12.720527648926 765.09283447266
-133.64335632324 -12.980895996094 767.13720703125
-133.86326599121 -13.09139251709 767.38140869141

**Comment by xinghaochen** [comment]
Hi, the centers can be calculated as in [here](https://github.com/xinghaochen/Pose-REN/blob/e7f42e1bb05523d2b99d83c2e2eabe45b5f0b894/src/utils/util.py#L244).
