### ISSUE TITLE
Look for more papers

### ISSUE THREAD

**Issue by yaoxinreaps** [xinghaochen/awesome-hand-pose-estimation#22]
Hi, the results of hands'17 competition are greatly improved now:
https://competitions.codalab.org/competitions/17356#results
could you please help to find the papers in the head of the list? Thank you!

**Comment by xinghaochen** [comment]
Hi, the entries on the leaderboard are not all disclosure methods. However, as far as I know, some methods have been published in CVPR'19, such as [CrossInfoNet](http://openaccess.thecvf.com/content_CVPR_2019/papers/Du_CrossInfoNet_Multi-Task_Information_Sharing_Based_Hand_Pose_Estimation_CVPR_2019_paper.pdf), [ResidualPEL](http://openaccess.thecvf.com/content_CVPR_2019/papers/Li_Point-To-Pose_Voting_Based_Hand_Pose_Estimation_Using_Residual_Permutation_Equivariant_CVPR_2019_paper.pdf).

You may dig into the leaderboard and find out more related papers. Free free to create a pull request if you find something interesting.
