### ISSUE TITLE
SynHand5M Dataset Joint Information

### ISSUE THREAD

**Issue by eparvizi** [xinghaochen/awesome-hand-pose-estimation#24]
Hello Xinghao,

Thanks for maintaining this useful repo. There seems to be a typo for SynHand5M dataset.
In the list of datasets, the number of joints for the SynHand5M dataset is listed as 21. However, upon further looking, I noticed they provide 1193 3D hand mesh vertices and couldn't find a mapping to extract the location of hand joints from the provided hand mesh vertices. Are you aware of the mapping between the two?

Thanks!

**Comment by xinghaochen** [comment]
Hi, sorry for the late reply. Actually I did not dig deep into this dataset and just inferred the number of joints as 21 according to some figures in the paper.  I will revise the repo and fix the information soon. Maybe you better send emails to the original authors for how to extract hand joints from mesh.
