### ISSUE TITLE
Evaluation on rgb hands?

### ISSUE THREAD

**Issue by moranli19** [xinghaochen/awesome-hand-pose-estimation#26]
Great work!  And thanks a lot. 
Here, I want to ask if there any evaluation and comparison code for RGB hands datasets such as the code for the NYU/ICVL/MSRA datasets?

**Comment by xinghaochen** [comment]
Hi, currently this repo does not contains evaluations on RGB-based hand pose estimation and any pull request on this would be highly appreciated.
