### ISSUE TITLE
The website of icvl dataset cannot open

### ISSUE THREAD

**Issue by LuciaXu** [xinghaochen/awesome-hand-pose-estimation#3]
Sorry for this kind of boring question. But I cannot open the website of icvl dataset, and cannot find it anywhere.

**Comment by xinghaochen** [comment]
Hi, recently ICVL has moved their project page to https://labicvl.github.io/hand.html. However, the download link of ICVL dataset seems still invalid. You may contact the [authors](https://labicvl.github.io/Members.html) to inquire related issues.
