### ISSUE TITLE
I have some question about MSRA dataset.

### ISSUE THREAD

**Issue by LYKlyk** [xinghaochen/awesome-hand-pose-estimation#33]
I find the "msra_test_list.txt" contain 76375 file, could you provide train list? What training files should I use？I found in many papers that they all said that they use theLeave one method, so they tend to train multiple models, so which model should be used?

**Comment by xinghaochen** [comment]
There are 9 subjects in MSRA dataset (P0~P8). "msra_test_list.txt" contains all samples from MSRA dataset. Leave-one-subject-out strategy is used to evaluate on MSRA dataset. More specifically, train on samples of 8 subjects and produce predictions on the rest one. In this way, you train 9 models and predict all hand poses for all samples.
