### ISSUE TITLE
something to update 

### ISSUE THREAD

**Issue by MengHao666** [xinghaochen/awesome-hand-pose-estimation#37]
The pdf of paper called "Weakly-supervised Domain Adaptation via GAN and Mesh Model for Estimating 3D Hand Poses Interacting Objects. "  is now open source.

http://openaccess.thecvf.com/content_CVPR_2020/papers/Baek_Weakly-Supervised_Domain_Adaptation_via_GAN_and_Mesh_Model_for_Estimating_CVPR_2020_paper.pdf

**Comment by xinghaochen** [comment]
Thanks! I have just updated the repo.
