### ISSUE TITLE
A dataset omitted

### ISSUE THREAD

**Issue by MengHao666** [xinghaochen/awesome-hand-pose-estimation#39]
A dataset called [Obman Dataset]( https://www.di.ens.fr/willow/research/obman/data/) is omitted
Its properties are as follows:
1.  Synthetic (S)
2.  RGB+ Depth
3.  Obj: Interaction with objects
4 ... ...

**Comment by xinghaochen** [comment]
Thanks. The preliminary information of Obman dataset was included in recent commit. Any pull request to add more information is welcome.
