### ISSUE TITLE
Hands 2017 paper

### ISSUE THREAD

**Issue by weiguochow** [xinghaochen/awesome-hand-pose-estimation#6]
Hi, xinghao, I have found there are a lot of paper form Hands 2017 challenge. Could you be able to download those papers? Thanks!!!

**Comment by xinghaochen** [comment]
Hi, if I am understanding you correctly, you are referring to the method descriptions of some entries in the challenge. As shown in Table 2 of [Depth-Based 3D Hand Pose Estimation: From Current Achievements to Future Goals](https://arxiv.org/pdf/1712.03917.pdf), some entries are already published (either in arXiv or peer-review conferences) and I think you can easily find them online. Meanwhile, some of the entries are just simply referred to the technical documents that are not publicly available.  I can not download these technical reports too. I think the best way to access these documents is to enquire the [challenge organizers](http://icvl.ee.ic.ac.uk/hands17/challenge/).

Hope it helps.

**Comment by weiguochow** [comment]
Thanks a lot!!!
