### ISSUE TITLE
add paper for ICCV2021

### ISSUE THREAD

**Issue by liwenssss** [xinghaochen/awesome-hand-pose-estimation#65]
PeCLR: Self-Supervised 3D Hand Pose Estimation from monocular RGB viaContrastive Learning

**Comment by Janus-Shiau** [comment]
This paper is already in the markdown, but the title is slightly different.
I have changed the title from "Self-Supervised 3D Hand Pose Estimation from monocular RGB via Contrastive Learning" to new title.

Thanks!

**Comment by ZhengdiYu** [comment]
> This paper is already in the markdown, but the title is slightly different. I have changed the title from "Self-Supervised 3D Hand Pose Estimation from monocular RGB via Contrastive Learning" to new title.
> 
> Thanks!

This paper seems to have code already: 
https://github.com/dahiyaaneesh/peclr

**Comment by xinghaochen** [comment]
> > This paper is already in the markdown, but the title is slightly different. I have changed the title from "Self-Supervised 3D Hand Pose Estimation from monocular RGB via Contrastive Learning" to new title.
> > Thanks!
> 
> This paper seems to have code already: https://github.com/dahiyaaneesh/peclr

Thanks!
