### ISSUE TITLE
I found an error

### ISSUE THREAD

**Issue by qhykwsw** [xinghaochen/awesome-hand-pose-estimation#7]
Hi, Depth-Based Hand Pose Estimation: Methods, Data, and Challenges is not from IJCV2018.

**Comment by xinghaochen** [comment]
Thanks for your reminder.
However, actually this paper was originally published in [ICCV 2015](https://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Supancic_Depth-Based_Hand_Pose_ICCV_2015_paper.pdf) and recently an extension version is published in [IJCV 2018](https://link.springer.com/content/pdf/10.1007%2Fs11263-018-1081-7.pdf).
