### ISSUE TITLE
Correction for two papers

### ISSUE THREAD

**Issue by geliuhao** [xinghaochen/awesome-hand-pose-estimation#8]
Hi Xinghao,

Thanks for maintaining this repo. It is very helpful for researchers. I want to correct two errors in your citation of my papers.

1. ECCV 2018: I typed the wrong tile on my homepage. The correct title is: "Point-to-Point Regression PointNet for 3D Hand Pose Estimation".

2. CVPR 2018: The correct title and author list are as follow:
Hand PointNet: 3D Hand Pose Estimation using Point Sets
Liuhao Ge, Yujun Cai, Junwu Weng, Junsong Yuan

Thank you!

**Comment by xinghaochen** [comment]
Hi Liuhao,

Thanks for your kind reminder. I have corrected the information for these two papers.
Congrats on your awesome work :)

**Comment by geliuhao** [comment]
Thanks!
