### ISSUE TITLE
BMVC 2018 oral

### ISSUE THREAD

**Issue by masabdi** [xinghaochen/awesome-hand-pose-estimation#9]
Hi Xinghao,

Thanks for adding my paper entitled "3D Hand Pose Estimation using Simulation and Partial-Supervision with a Shared Latent Space" to your list.

Just wondering if you could please update it to Oral?

Cheers.

**Comment by xinghaochen** [comment]
Hi Masoud,

I have just updated the information of your BMVC paper.
Congrats on your great work :)
