### ISSUE TITLE
SHOWMe Paper (ICCV 2023 /ACVR  Oral Paper)

### ISSUE THREAD

**Issue by anilesec** [xinghaochen/awesome-hand-pose-estimation#92]
Hello,

This paper will be in the proceedings of ICCVW  and it will be presented in ACVR workshop oral.
Could you please add it to the ICCV 2023 list? Below are the required links

**SHOWMe: Benchmarking Object-agnostic Hand-Object 3D Reconstruction**
[Anilkumar Swamy](https://europe.naverlabs.com/people_user/Anilkumar-Swamy/),  [Vincent Leroy](https://europe.naverlabs.com/people_user/Vincent-Leroy/),  [Philippe Weinzaepfel](https://europe.naverlabs.com/people_user/Philippe-Weinzaepfel/),  [Fabien Baradel](https://europe.naverlabs.com/people_user/Fabien-Baradel/?asp_highlight=Fabien+Baradel&p_asid=9),  [Salma Galaaoui](https://europe.naverlabs.com/people_user_naverlabs/Salma-Galaaoui/), [Romain Bregier](https://europe.naverlabs.com/people_user/Romain-Br%C3%A9gier/), [Matthieu Armando](https://europe.naverlabs.com/people_user_naverlabs/Matthieu-armando/), [Jean-Sebastien Franco](https://morpheo.inrialpes.fr/~franco/), [Gregory Rogez](https://europe.naverlabs.com/people_user/Gregory-Rogez/)

[[Paper](https://arxiv.org/pdf/2309.10748.pdf)] [[Project Page](https://europe.naverlabs.com/research/showme)] [[Code](https://github.com/naver/showme/tree/main)] [[Dataset](https://download.europe.naverlabs.com/showme/)] 

Thank you in Advance!

**Comment by xinghaochen** [comment]
Done. Thanks.
